name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
   test:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - uses: actions/setup-python@v2
         with:
           python-version: '3.9'
       - name: Install dependencies
         run: |
           pip install -U pip
           pip install pytest # flake8 black isort
           # pip install -e ".[dev]"
       - name: Run pytest
         run: |
           pytest
       # - name: Run flake8
       #   run: |
       #     flake8 .
       # - name: Run black
       #   run: |
       #     black . --diff
       # - name: Run isort
       #   run: |
       #     isort .
